#
#   - cpan2rpm -
#   This spec file was automatically generated by cpan2rpm [ver: 2.028]
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define pkgname cpan2rpm
%define filelist %{pkgname}-%{version}-filelist
%define NVR %{pkgname}-%{version}-%{release}
%define maketest 1

Name:      cpan2rpm
Summary:   cpan2rpm - A Perl module packager
Version:   2.028
Release:   0.5
Vendor:    Erick Calder <ecalder@cpan.org>
Packager:  Arix International <cpan2rpm@arix.com>
License:   GPLv2
Group:     Applications/CPAN
URL:       http://www.cpan.org
BuildRoot: %{_tmppath}/%{name}-%{version}-%(id -u -n)
buildArch: noarch
BuildRequires: perl-libwww-perl
BuildRequires: perl(ExtUtils::MakeMaker)
BuildRequires: fakeroot

Requires:  %([ -e /etc/SuSE-release -o -e /etc/UnitedLinux-release ] && SuSE=1;ver=`rpm -q rpm --qf %%{version}|awk -F . '{print $1}'`;[ $ver -le 3 -o -n "$SuSE" ] && echo rpm || echo rpm-build)
Requires:  %{_bindir}/rpmsign
Source:    ftp://ftp.arix.com/cpan2rpm-2.028.tar.gz
Patch0:	   cpan2rpm-2.028-pod-text.patch
Patch1:    cpan2rpm-2.028-vendor.patch

%description
This script generates an RPM package from a Perl module.  It uses the standard RPM file structure and creates a spec file, a source RPM, and a binary, leaving these in their respective directories.

The script can operate on local files, directories, urls and CPAN module names.  Install this package if you want to create RPMs out of Perl modules.

The syntax for cpan2rpm supports multiple *distribution* names, which can take one of four different forms:

=over

=item 1. a CPAN module name (e.g. XML::Simple) - When a module name is passed, the script will "walk" search.cpan.org to determine the latest distribution.  If an exact match is not found, the CPAN module is used to make this determination.  If you have not yet configured this module, please refer to the REQUIREMENTS section below for further instructions.

=item 2. a URL (both http:// and ftp:// style locators will work) - In this and the above case, an automatic download of the needed tarball is performed (see notes for how).  The tarball is deposited in the SOURCES directory.

=item 3. a path to a tarball (e.g. /tmp/XML-Simple-1.05.tar.gz) - In this case, the tarball indicated gets copied to the SOURCES directory.

=item 4. a directory path - The directory specified must contain a Makefile.PL.  If the user intends to build a package from a directory (i.e. user does NOT specify --spec-only), the commands:

    perl Makefile.PL
    make
    make dist

will be performed in that directory in order to create the tarball necessary for package creation.

=back

#
# This package was generated automatically with the cpan2rpm
# utility.  To get this software or for more information
# please visit: http://perl.arix.com/
#

%prep
%setup -q -n %{pkgname}-%{version} 
%patch0 -p1 -b .parser
%patch1 -p1 -b .vendor
chmod -R u+w %{_builddir}/%{pkgname}-%{version}

%build
grep -rsl '^#!.*perl' . |
grep -v '.bak$' |xargs --no-run-if-empty \
%__perl -MExtUtils::MakeMaker -e 'MY->fixin(@ARGV)'
CFLAGS="$RPM_OPT_FLAGS"
# Add INSTALLDIRS=vendir for perl 5.10, to avoud /usr/local/lib
%{__perl} Makefile.PL  INSTALLDIRS=vendor `%{__perl} -MExtUtils::MakeMaker -e ' print qq|PREFIX=%{buildroot}%{_prefix}| if \$ExtUtils::MakeMaker::VERSION =~ /5\.9[1-6]|6\.0[0-5]/ '`
%{__make} 
%if %maketest
%{__make} test
%endif

%install
[ "%{buildroot}" != "/" ] && rm -rf %{buildroot}

%{makeinstall} `%{__perl} -MExtUtils::MakeMaker -e ' print \$ExtUtils::MakeMaker::VERSION <= 6.05 ? qq|PREFIX=%{buildroot}%{_prefix}| : qq|DESTDIR=%{buildroot}| '`

cmd=/usr/share/spec-helper/compress_files
[ -x $cmd ] || cmd=/usr/lib/rpm/brp-compress
[ -x $cmd ] && $cmd

# SuSE Linux
if [ -e /etc/SuSE-release -o -e /etc/UnitedLinux-release ]
then
    %{__mkdir_p} %{buildroot}/var/adm/perl-modules
    %{__cat} `find %{buildroot} -name "perllocal.pod"`  \
        | %{__sed} -e s+%{buildroot}++g                 \
        > %{buildroot}/var/adm/perl-modules/%{name}
fi

# remove special files
find %{buildroot} -name "perllocal.pod" \
    -o -name ".packlist"                \
    -o -name "*.bs"                     \
    |xargs -i rm -f {}

# no empty directories
find %{buildroot}%{_prefix}             \
    -type d -depth                      \
    -exec rmdir {} \; 2>/dev/null

%{__perl} -MFile::Find -le '
    find({ wanted => \&wanted, no_chdir => 1}, "%{buildroot}");
    print "%doc perl.req.patch Changes README.redhat6 LICENSE README";
    for my $x (sort @dirs, @files) {
        push @ret, $x unless indirs($x);
        }
    print join "\n", sort @ret;

    sub wanted {
        return if /auto$/;

        local $_ = $File::Find::name;
        my $f = $_; s|^\Q%{buildroot}\E||;
        return unless length;
        return $files[@files] = $_ if -f $f;

        $d = $_;
        /\Q$d\E/ && return for reverse sort @INC;
        $d =~ /\Q$_\E/ && return
            for qw|/etc %_prefix/man %_prefix/bin %_prefix/share|;

        $dirs[@dirs] = $_;
        }

    sub indirs {
        my $x = shift;
        $x =~ /^\Q$_\E\// && $x ne $_ && return 1 for @dirs;
        }
    ' > %filelist

[ -z %filelist ] && {
    echo "ERROR: empty %files listing"
    exit -1
    }

%clean
[ "%{buildroot}" != "/" ] && rm -rf %{buildroot}

%files -f %filelist
%defattr(-,root,root)

%changelog
* Sat Jul 13 2013 Nico Kadel-Garcia <nkadel@gmail.com>
- Add rpmsign dependency for Fedora 19.

* Mon Apr  9 2012 Nico Kadel-Garcia <nkadel@gmail.com>
- Add perl(ExtUtils::MakeMaker) build requirement
- Add INSTALLDIRS=vendor and cpan2rpm patch to include it for new .spec files

* Wed Feb  8 2012 Nico Kadel-Garcia <nkadel@gmail.com>
- Patch to Replace Pod::Text with Pod::Parser to allow compilation on RHEL 6
- Update license notice to GPLv2 to match original license

* Fri Jun 17 2005 ekkis@beowulf
- Initial build.
